version: '3'
services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
  hass-socat:
    image: alpine/socat:latest
    container_name: hass-socat
    entrypoint: "socat tcp-listen:8122,fork,reuseaddr tcp-connect:192.168.0.100:8123"
    depends_on:
      - proxy
    environment:
      - VIRTUAL_PORT=8122
      - VIRTUAL_HOST=homeassistant.r.pi
    network_mode: bridge
    ports:
      - 8122:8122
    restart: unless-stopped