version: '3'
services:
  unms:
    image: nico640/docker-unms:latest
    restart: always
    ports:
      - 6000:80
#      - 443:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - unms:/config
volumes:
  unms: