services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
volumes:
  data:
